import type { Metadata } from "next";
import SessionWrapper from "./session-wrapper";
import LayoutVisibilityWrapper from "@/components/shared/LayoutVisibilityWrapper";
import { QueryProvider } from "@/providers/query-provider";
import { SocketProvider } from "@/providers/socket-provider";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#000000] antialiased">
        <SessionWrapper>
          <QueryProvider>
            <SocketProvider>
              <LayoutVisibilityWrapper>{children}</LayoutVisibilityWrapper>
            </SocketProvider>
          </QueryProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
