import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import NewsletterSection from "@/components/shared/NewsletterSection";
import SessionWrapper from "./session-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#000000] antialiased">
        <SessionWrapper>
          <Navbar />
          {children}
          <NewsletterSection />
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
